### ISSUE TITLE
Defect loading limitation 

### ISSUE THREAD

**Issue by fasterfish** [reportportal/service-ui#103]
When loading a bug from BTS, address of the server must contain a point.
We use next BTS address: http://tfs:8080/tfs.

![screenshot_2_480](https://cloud.githubusercontent.com/assets/18389889/23215627/e39ad4aa-f934-11e6-8ade-c9b2888310ce.png)

Can you remove this restriction?

Thanks.

**Comment by DzmitryHumianiuk** [comment]
@lexecon

**Comment by lexecon** [comment]
Fixed in version 3.0
