### ISSUE TITLE
Is it possible to customize test results page to include additional attribute from test parameters

### ISSUE THREAD

**Issue by nnilakh** [reportportal/service-ui#1338]
Currently test result page has the following attributes:
Method Type
Name
Status
Start
Defect Type

I wanted to add one more attribute relevant to each tests - 'Number of assertions'.  This value is available for each test in 'Test Parameters'. Is there a way to customize the reportportal ui to include a new attribute in test results.

**OR**

Can I change the name and value of any of existing attribute, to reflect the new attribute that I need?

**Comment by DzmitryHumianiuk** [comment]
@nnilakh 
you can append this data into description of test case.

but this is kind of custom implementation of agent. Example here: 
https://github.com/reportportal/example-java-TestNG/blob/master/logback/src/main/java/com/epam/rp/tests/extension/ParameterizedTest.java#L76

![image](https://user-images.githubusercontent.com/11332788/55895255-766bba80-5bc4-11e9-8bee-54774635d2d9.png)

![image](https://user-images.githubusercontent.com/11332788/55895301-8e433e80-5bc4-11e9-94ba-2622c6c03541.png)

**Comment by nnilakh** [comment]
@DzmitryHumianiuk Thanks that worked.

Is it possible to update the Launch description in similar way. I wanted to update the description for the launch - 'rp.description' dynamically, to display total number of assertions in the launch. Can I do that by overriding any method.?

**Comment by DzmitryHumianiuk** [comment]
@nnilakh 
https://github.com/reportportal/agent-java-testNG#code-example-how-to-overload-params-in-run-time
