### ISSUE TITLE
Cannot enter password longer than 25 characters

### ISSUE THREAD

**Issue by pavel-gatilov-epam** [reportportal/service-ui#1365]
The Password field on the log in screen is limited to 25 characters. This makes sign in impossible in case I have a password that is longer than 25 chars. In my case, the account is linked to a Windows domain and the password set in the domain was 32 chars. I had to change the password for the domain account.

Would you mind removing or at least significantly increasing the password length limit on the sign in screen?

**Comment by evjlobanova** [comment]
Fixed in version 5.0
