### ISSUE TITLE
Opening testcase after filtering it with "filter.cnt.name=/foo" returns error

### ISSUE THREAD

**Issue by rplevka** [reportportal/service-ui#1748]
The item can't be opened. All I get is a message:

Item is not found
Failed to load data for launches table

after removing the the problematic filter portion of the URL (`&filter.cnt.name=%2Ffoo`), it works.

steps to reproduce:
have test cases with `/` in name (e.g. `fooTestClass/foo/test_1`)
now try to filter only those with `/foo` in the name:
Filter name cnt: "/foo"

Click on any of the filtered test case.

**Comment by evjlobanova** [comment]
@svettsova Valya, please try to reproduce it for ver 5.1?

**Comment by svettsova** [comment]
issue is not reproducible in 5.0 and 5.1 versions
@rplevka could you please recheck the issue?
