### ISSUE TITLE
Device Statistic widget used in testing 

### ISSUE THREAD

**Issue by newbie-qa** [reportportal/service-ui#1784]
First, thank you for this very helpful tool. I find it very useful when I run my automation test. As I basically started to use the tool, the available widgets are very good however I am missing one type of widget.

Is there a possibility to have a device/browser information displayed on my dashboard ? Like a widget?  That would be very cool to have.

Many thanks!

**Comment by evjlobanova** [comment]
@newbie-qa You can add attributes 'browser: Name' 'device: Name' for test cases executions and configure a widget 'Component health check widget' https://reportportal.io/docs/Component-health-check
