### ISSUE TITLE
username and password in clear text in form data POST to uat/sso/oauth/token

### ISSUE THREAD

**Issue by sridharangopal** [reportportal/service-ui#1997]
when trying to login into the UI, I see the username and password in clear text in the form data being posted to uat/sso/oauth/token. I thought this was fixed somewhere in the previous version. Is this expected behavior? Please see screenshot. Any guidance on how to avoid exposing creds in clear text is much appreciated. 

I believe this is the line of code that is contributing to this behavior:
https://github.com/reportportal/service-ui/blob/8729489f977577f83855d121a040ebb308d5c704/app/src/controllers/auth/sagas.js#L107

![Screen Shot 2019-09-10 at 2 02 42 PM](https://user-images.githubusercontent.com/6555085/64638688-41ae9a00-d3d4-11e9-935f-ab5654fa54d9.png)

**Comment by loadtheaccumulator** [comment]
Please also see, https://github.com/reportportal/service-authorization/issues/86.

**Comment by DzmitryHumianiuk** [comment]
@sridharangopal  which version of `service-ui`you use?

**Comment by DzmitryHumianiuk** [comment]
fixed in v5
https://github.com/reportportal/reportportal/issues/626

**Comment by DzmitryHumianiuk** [comment]
@sridharangopal @loadtheaccumulator 
try
`service-api` 4.3.11
`service-ui` 4.3.7
