### ISSUE TITLE
[Widget] Responsive design issue

### ISSUE THREAD

**Issue by dubilyer** [reportportal/service-ui#2089]
As you can see on attached screenshot, there's an overlap between axis X labels.
You can easily reproduce it by creating a 7+ bars Launch statistic chart widget and reducing a window.

RP version - 4.3.0
Browsers - Chrome 77, Edge 44

![image](https://user-images.githubusercontent.com/16655093/66264852-34d76780-e815-11e9-9072-00923b1b0395.png)

**Comment by dubilyer** [comment]
Guys, can somebody take a look, please?

**Comment by evjlobanova** [comment]
Duplicate of https://github.com/reportportal/reportportal/issues/753
