### ISSUE TITLE
Cannot access login page: 307 redirection error

### ISSUE THREAD

**Issue by idonca** [reportportal/service-ui#2182]
Hello,

we installed v5 reportportal helm chart, we have everything up and running in our cluster.
The problem is when we want to access the login page: IP/ui, is redirecting continuously and we receive network error.

More details below:
![issue1](https://user-images.githubusercontent.com/56868732/68311897-eb4f9600-00ba-11ea-8328-2da23866d1f7.PNG)
![issue2](https://user-images.githubusercontent.com/56868732/68311909-ef7bb380-00ba-11ea-9124-94e14e78b77e.PNG)
![issue3](https://user-images.githubusercontent.com/56868732/68311918-f276a400-00ba-11ea-899b-c8bb22c7ef6b.PNG)

In the last screenshot you can see that there is no output on the current version regarding the services that are running: e.g: ui, api...

I access also directly the pods with the port but no help, still redirecting.

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello,

**Comment by AlehB** [comment]
Hello Ionut,

RP5 K8s Helm chart installation assumes the use of Nginx Ingress controller, which creates a Load Balancer in the Cloud. All Ingress rules are written for this controller. Thus, to get an access to RP ui you do not need to go through IP:port/ui, but LB address itself

Best Regards,
Aleh

**Comment by idonca** [comment]
Hello Aleh, 

We did also like that, but still redirecting. 
We accessed also only the LB address and we have the same issue (redirecting error).

Thank you,
-Ionut

**Comment by AlehB** [comment]
Do you use default nginx configuration?

Could you please check the logs of API / UAT containers?

Thank you,
Aleh

**Comment by idonca** [comment]
Yes, we used the default nginx configuration and also we tried to access the UI via a nodeport, the behavior was exactly on both tries. 
Attached are logs from uat and api containers.

Thank you,
-Ionut

[logs-from-uat.txt](https://github.com/reportportal/service-ui/files/3823593/logs-from-uat.txt)
[logs-from-api.txt](https://github.com/reportportal/service-ui/files/3823594/logs-from-api.txt)

**Comment by AlehB** [comment]
I see no errors in your log files.
Anyway there should be the services versions displayed on the main page.
 @pbortnik , @avarabyeu , do you happen to know what can be a reason of the empty services field?

**Comment by idonca** [comment]
Hello,
Any updates? 

Thanks

**Comment by AlehB** [comment]
Hello Ionut,

We assume you have an issue with some service. Could you please check the Index log as well?

Thank you,
Aleh

**Comment by idonca** [comment]
Hello Aleh,

Attached is also index log file.
[logs-from-index-in-index-745cbdf98b-jb9lt.txt](https://github.com/reportportal/service-ui/files/3830639/logs-from-index-in-index-745cbdf98b-jb9lt.txt)

Thanks,
-Ionut

**Comment by avarabyeu** [comment]
all the requests that are supposed to reach UI component are actually routed to index component. 
Could you please share your ingress configuration and UI service logs.

**Comment by idonca** [comment]
Hello @avarabyeu,

Attach you can find the ingress config and also the logs from the UI service.

Thanks,
-Ionut
[logs-from-ui-in-ui-5f599d55cd-rhmvp.txt](https://github.com/reportportal/service-ui/files/3831660/logs-from-ui-in-ui-5f599d55cd-rhmvp.txt)

[ingress.txt](https://github.com/reportportal/service-ui/files/3831662/ingress.txt)

**Comment by idonca** [comment]
Hello,

I updated the files from your latest commits, but no luck. Still receiving redirecting errors.
Any updates from your side?

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut,

I'm wondering why you are having "123" in your Ingress configuration. Please try 'kubectl describe ing reportportal-gateway-ingress' and make sure you have smth similar to the configuration attached

[Ingress example.txt](https://github.com/reportportal/service-ui/files/3850550/Ingress.example.txt)

Thank you,
Aleh

**Comment by idonca** [comment]
Hello Aleh,

That was only for testing purpose. Was a version for testing.
Now we have the default config version for our ingress, exactly the one attached.

[ingress-config.txt](https://github.com/reportportal/service-ui/files/3850622/ingress-config.txt)

Thank you,
-Ionut

**Comment by idonca** [comment]
Hello,

Any news?

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut

You Ingress configuration looks good, except one thing. On our both installations (AWS and GCP) we have not LB name in the "Address" field, but a public IP.

Your issue can be caused by some misconfiguration of your LB / Nginx Ingress Controller.
By the way, what version of Nginx Ingress Controller you use?

Thank you
Aleh

**Comment by idonca** [comment]
Hello guys,

So we installed the following chart, that is attached. 
And the following version of requirements:
$ cat requirements.yaml
dependencies:
  - name: postgresql
    version: 3.9.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.installdep.enable

  - name: rabbitmq-ha
    version: 1.18.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.installdep.enable

  - name: elasticsearch
    version: 7.3.2
    repository: https://helm.elastic.co
    condition: elasticsearch.installdep.enable

  - name: minio
    version: 2.5.12
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: minio.installdep.enable

I have one question: did you use the requirement applications as external (as cloud services)?
Or did you test also with the charts locally?

Thank you,
-Ionut

[test-reporting-chart.zip](https://github.com/reportportal/service-ui/files/3886471/test-reporting-chart.zip)

**Comment by AlehB** [comment]
Hello Ionut,

We tested both options. At first with charts locally, and then with a cloud service (AWS RDS)

Thank you
Aleh

**Comment by idonca** [comment]
hello Aleh,

and I guess, both options were succeeded, no?
Could you please take a look at our chart, I mean at the values.yml especially? 

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut,

Yes, and we still have one of these installations in use

Of course, please send it to me

Thank you
Aleh

**Comment by idonca** [comment]
Hello Aleh,

Attached, you can find out the values.yml file.


[values.txt](https://github.com/reportportal/service-ui/files/3890528/values.txt)
Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut,

Firstly I would recommend you to double-check your endpoints for the ReportPortal dependencies.

By default it should look like:
<postgresql_chart_name>-postgresql.default.svc.cluster.local
<rabbitmq_chart_name>-rabbitmq-ha.default.svc.cluster.local
http://<minio-release-name>.default.svc.cluster.local:9000

As far as I see you have:
rabbitmq-reportportal-rabbitmq-ha.reportportal
postgresql-reportportal-postgresql.reportportal
http://minio-reportportal.reportportal.svc.cluster.local:9000

Did you override the clusterDomain name from cluster.local to reportportal? Why do you still have the old one for MinIO then..?
Please check your RabbitMQ / PostgreSQL installation outputs to get the correct endpoints.

Thank you
Aleh

**Comment by CNXautomation** [comment]
Hello Aleh,

I put in the values the name of the services that are running in that kubernetes namespace.
If I change in deployment.yaml services and add the ending default.svc.cluster.local , (eg. postgresql.default.svc.cluster.local) it returns errors that the host cannot be found.

I changed now also minio to run to minio-reportportal.reportportal:9000 and it's fine.
So now, all the services are running with the ending reportportal (not default.svc.cluster.local)

The redirection errors still persist.

Thank you,
-Ionut

**Comment by idonca** [comment]
I was logged in with another user in github. :)

**Comment by idonca** [comment]
So, we made again a fresh install and we are receiving the same redirect error.
I do not know why is not finding url/ui, it saying that is not finding the ui service...

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut,

Most likely it is some misconfiguration of your lb / Nginx Ingress Controller then.
Please make sure your version supports all annotations in their current regular expressions

I would also recommend you to try to make a fresh install with no any changes (namespaces and so on). Just following the guide

Thank you
Aleh

**Comment by idonca** [comment]
Hello Aleh,

We are using 0.21.0 version of ingress-nginx. It said that the annotation `nginx.ingress.kubernetes.io/rewrite-target`
has been changed for the above versions of ingress-nginx. I also change the ingresses and commented out that annotation, but still no luck.

With which ingress-nginx version you deployed locally the reportportal chart?

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut,

Exactly. This is what I mentioned a week ago.
Starting in 0.22.0, Ingress definitions using the annotation nginx.ingress.kubernetes.io/rewrite-target are not backwards compatible with previous versions. We use captured groups for this annotation, and this is very important for RP Ingress to work properly.
0.21.0 is quite outdated

We have 0.25.0

Thank you,
Aleh

**Comment by idonca** [comment]
Hello Aleh,

Unfortunately, also after upgrading the ingress-nginx to 0.25.0 version we still have the same redirect problem. We did a fresh install and still the same problem.
Also the code is up-to-date.

Thank you,
-Ionut

**Comment by AlehB** [comment]
Hello Ionut,

The latest code updates aren't supposed to to fix your issue. It smth with your Nginx or LoadBalancer but it hard to say what it can be, based on your logs with no errors. The basic RP configuration works fine on AWS and GCP, and it was tested.
Have you changed anything during your fresh installation, or you just followed the guide?

Thank you,
Aleh

**Comment by evjlobanova** [comment]
@idonca if you still have a prpblem, please drop us a letter to 
![image](https://user-images.githubusercontent.com/30413511/72528972-58cb3000-387d-11ea-8833-f6eacfdcccbe.png).
We can propose you a paid suppport.

**Comment by dharma-keyutech** [comment]
> Hello,
> 
> we installed v5 reportportal helm chart, we have everything up and running in our cluster.
> The problem is when we want to access the login page: IP/ui, is redirecting continuously and we receive network error.
> 
> More details below:
> ![issue1](https://user-images.githubusercontent.com/56868732/68311897-eb4f9600-00ba-11ea-8328-2da23866d1f7.PNG)
> ![issue2](https://user-images.githubusercontent.com/56868732/68311909-ef7bb380-00ba-11ea-9124-94e14e78b77e.PNG)
> ![issue3](https://user-images.githubusercontent.com/56868732/68311918-f276a400-00ba-11ea-899b-c8bb22c7ef6b.PNG)
> 
> In the last screenshot you can see that there is no output on the current version regarding the services that are running: e.g: ui, api...
> 
> I access also directly the pods with the port but no help, still redirecting.
> 
> Thank you,
> -Ionut

Hi idonca, are you able to resolve the issue...?

**Comment by olegz-codefresh** [comment]
I have the same issue with running in docker.

**Comment by AlehB** [comment]
Hi @olegz-codefresh ,

Please make sure that you followed the documentation exactly, and there no any errors in RP services

**Comment by Aman-singh-wq** [comment]
Hi Team 

Please let me know if anyone able to fix ERR_TOO_MANY_REDIRECTS  error in report-portal.
