### ISSUE TITLE
Opening report portal login screen may stuck

### ISSUE THREAD

**Issue by groov1kk** [reportportal/service-ui#2263]
Opening report portal's login screen may stuck and takes a lot of time. To reproduce this bug you need to clear browser's cache.

Steps to reproduce:
1. Clear browser's cache (for example, in chrome: history -> clear history -> remove images and other files from cache)
2. open https://dev.reportportal.io/ui/#login

Expected result:
Login page should be open immediately

Actual result:
Browser stuck and wait more that 1 minute to open the page
Console contains errors. See screenshot

<img width="1641" alt="Снимок экрана 2019-12-11 в 17 42 21" src="https://user-images.githubusercontent.com/9006447/70631948-07f16780-1c3f-11ea-9e85-92e4e01208fa.png">

**Comment by DzmitryHumianiuk** [comment]
UI uses https://semver.org/ approach to define new available builds.

Above applicated deployed with version name, started with letters, against the rest of services which start with numbers.

that's covered now from app side,
but also follow Version Semantic for custom deployments

**Comment by alizaidi96** [comment]
I'm actually fed up with this now. At our organisation nurture.farm, we thought we will use Reportportal for our build reports but the issues are just endless. Setup was okay but never works on restart.
Have tried all the approaches mentioned. Maxed out memory requirements to 10GB+.
Nothing works. Please fix your product if you don't want business impacts!

**Comment by DzmitryHumianiuk** [comment]
@alizaidi96 First off, thank you for interest in ReportPortal.
ReportPortal is a free and open sourced solution, distributed under Apache 2.0 license, which means AS IS.

If you would like to receive our dedicated help and assistance, please drop as email at support@reportportal.io
so we can arrange the call and discuss the offering details.

I am very saddened by the fact that you, unlike thousands of other companies, are unable to install and configure our open and free solution.

ReportPortal is a complex micro-services based application, designed for the heavy load and near-real-time reporting.
It requires a minimum devops/cloud knowledge to set it up properly for the long-run.
The docker-compose file, which you most probably use is designed for a demo purposes only.

**Comment by DzmitryHumianiuk** [comment]
@alizaidi96 k8s setup is a right way to go.
we definitely will compiled versions for the ARM (apple silicon included) in a while,
but currently team focuses on other priorities.

please follow https://github.com/reportportal/reportportal/issues/1815 for related request.
