### ISSUE TITLE
Cannot set environment variables for consul/registry host and port

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/service-ui#2289]
I am deploying within a Kubernetes cluster and we are currently stuck with version 1.14+ on the server side.  I know that there is an alpha fix in kubernetes 1.18 to allow for environment variables to be set within the borne shell that utilize periods / dots in their name.  Right now, there does not seem to be a work around with our situation and I am having difficulty working out what file could be used to override / set these variables.

I had attempted to create a /public/.env file with the appropriate values within it for the service-ui service however, these values are not being picked up by the environment or the application at startup.  When I shell in I can see some of the variables that I had set that do not contain the period / dot in the name as being set in the environment.

Is there a method to set the variables and have them read as a part of the main.go process?  If so, what file is needed and what values are supported there?

Thanks,
Scott

**Comment by evjlobanova** [comment]
@AlehB could you please help @sspieker-cc .
@sspieker-cc as a possible decision we can propose you to update a current version of your Reportportal to the latest one (stable RC 6 of version 5)

**Comment by AlehB** [comment]
Hi @sspieker-cc ,

**Comment by AlehB** [comment]
Hi @sspieker-cc ,
First of all, we would recommend you to start with our ReportPortal 5 Helm chart installation for Kubernetes. https://github.com/reportportal/kubernetes/tree/master/reportportal/v5
There no cosul anymore, and there no need to change env. variables for UI service
Best wishes,
Aleh
