### ISSUE TITLE
[Firefox] Close Icon is very big after selecting a Launch

### ISSUE THREAD

**Issue by skinner969** [reportportal/service-ui#2389]
**Steps:**

1. Open RP in Firefox(Reproduced for 76.0.1)
2. Go to any project
3. Check/Select one launch

**Actual:**
Close icon is filling the whole screen
![изображение](https://user-images.githubusercontent.com/9725495/82452629-314cd400-9ab8-11ea-9e23-2a37390eeaf5.png)
**Expected:**
Close icon is small

**Current version:API Service: 5.2.1;Index Service: 5.0.7;Authorization Service: 5.2.1;Service UI: 5.2.0;**
**Not reproduced in chrome.**
**Reproduced in firefox.**

**Comment by DiscoElevator** [comment]
Hello, @skinner969 
Thank you for reporting this issue.
The fix will be released with the version 5.3, but I don't know the timeline.
Feel free to reopen this issue if you have any additional questions regarding it.
