### ISSUE TITLE
create dashboard from debug report

### ISSUE THREAD

**Issue by willyhalim** [reportportal/service-ui#2566]
Is there any way to create dashboard based on "Debug" report . At the moment it seems only works against "Launch" report

**Comment by DzmitryHumianiuk** [comment]
@willyhalim there is no.
all widgets/dashboards has pre-defined filter to ignore launches from `debug` mode.
we assume `debug` as a sand-box, which should not affect general scope of executions.

you can transfer your launch from debug to general tab with one click via the menu button.

in case if you don't want to see this launch in the list of all launches you can create a filter based on specific criteria and take a look only on required list.

closing ticket to now.
but it would be nice, if you @willyhalim can describe your case in details and why you need dashboards from debug seciont
