### ISSUE TITLE
History view broken

### ISSUE THREAD

**Issue by andikfil** [reportportal/service-ui#282]
1. Button is hidden to load more items 
2. Loading state after click on button

Issue is reproduced in build: 3.0.5

![history_view_broken](https://user-images.githubusercontent.com/22031074/28618566-808724a2-720d-11e7-9bf2-71f05d86ee49.png)

**Comment by DzmitryHumianiuk** [comment]
@andikfil could you please specify steps?

can't get the flow which you described above.

**Comment by andikfil** [comment]
1. Open any launch that contains at least 50 tests/items in view
2. Click History button and try to load all tests

**Comment by DzmitryHumianiuk** [comment]
https://rp.epam.com/ui/#default_project/launches/all|page.page=172&page.size=50&page.sort=start_time%2CDESC/531f9852e4b02fba21edfc45|page.page=1&page.size=50&page.sort=start_time%2CASC/531f98a5e4b02fba21ee0489|page.page=1&page.size=50&page.sort=start_time%2CASC/531f98a9e4b02fba21ee0519?page.page=1&page.size=50&page.sort=start_time%2CASC
