### ISSUE TITLE
make get-build-deps is failing

### ISSUE THREAD

**Issue by varundunga** [reportportal/service-ui#2953]
Hi Team,

Im trying to build service ui using dockerfile-full and getting the below error. the get-build-deps task in makefile is failing. Below is the error:

` > [build-backend 4/7] RUN make get-build-deps:                                                                                                                             
#13 0.250 curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "/go/bin" v1.36.0                                             
#13 0.383 golangci/golangci-lint info checking GitHub for tag 'v1.36.0'
#13 0.782 golangci/golangci-lint info found version: 1.36.0 for v1.36.0/linux/amd64
#13 4.090 golangci/golangci-lint info installed /go/bin/golangci-lint
#13 4.099 go get github.com/avarabyeu/releaser mvdan.cc/gofumpt/gofumports
#13 6.272 go: downloading mvdan.cc/gofumpt v0.2.1
#13 6.483 go: downloading github.com/avarabyeu/releaser v0.0.0-20170822143458-d7f1dd74c9f0
#13 6.562 go get: module mvdan.cc/gofumpt@upgrade found (v0.2.1), but does not contain package mvdan.cc/gofumpt/gofumports
#13 6.565 make: *** [Makefile:30: get-build-deps] Error 1
------
executor failed running [/bin/sh -c make get-build-deps]: exit code: 2`

Please help me with this

**Comment by AmsterGet** [comment]
Hello @varundunga!
Now we are in progress of removing go lang from this service and it will be replaced by nginx within next release.
But if you are trying to build the image from the `master` branch you can use [this](https://github.com/reportportal/service-ui/commit/551f4af860094ae09c3adb9cff19fe5f623cebb6) temporary fix.
On the other hand, you can always use the latest published image from docker hub (https://hub.docker.com/r/reportportal/service-ui/tags).

**Comment by varundunga** [comment]
Thanks....Its working now
