### ISSUE TITLE
Component Health Check - Needs to wrap text

### ISSUE THREAD

**Issue by mdfarhanin** [reportportal/service-ui#3132]
Since there is no option to text wrap - It is difficult to see reports
Have ability to expand table cell
<img width="276" alt="Screen Shot 2022-06-10 at 1 12 45 PM" src="https://user-images.githubusercontent.com/15947334/173126175-6b635eda-5ca4-4d1b-bede-d69364fc27db.png">

**Comment by DzmitryHumianiuk** [comment]
@mdfarhanin hey, do you mean `move the text to the next line if not fitted` under `wrap`?

**Comment by mdfarhanin** [comment]
@DzmitryHumianiuk - Yes

**Comment by AmsterGet** [comment]
Hello @mdfarhanin !
We will discuss this option with the UX team.
Stay tuned.

**Comment by AmsterGet** [comment]
Hello @mdfarhanin !
We have discussed your suggestion with the UX team and have decided to implement the 'immediate tooltip' for these elements as a quick fix in version 5.8.
Wrapping this text won't look nice in the current implementation, as it will be hard to read for small widgets.
In future versions, we plan to introduce updated widgets, so your suggestions will be taken into account when implementing them.
Thank you for your patience.
