### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by idRomanUdka** [reportportal/service-ui#326]
1. Open tab 'Launches'
2. Press down on mouse wheel on first record and move cursor to area with grey background (right side)
[normal_view](https://drive.google.com/file/d/0BzonnHNMLwEtTmRWUVB2RFcweTQ/view?usp=sharing)
[actual_view](https://drive.google.com/file/d/0BzonnHNMLwEtWUV2SjZYNl9nU2s/view?usp=sharing)

Additional information: 
window.screen.availHeight - **864**
window.screen.availWidth - **1536**
Browser - **Chrome Version 60.0.3112.90 (Official Build) (64-bit)**
Report Portal -  **Build: 3.1.1**

**Comment by lexecon** [comment]
fixed in 3.3 version UI service
