### ISSUE TITLE
Minor UI table fixes.

### ISSUE THREAD

**Issue by admizh** [reportportal/service-ui#51]
![table minor changes](https://cloud.githubusercontent.com/assets/6014483/20519041/c78e57a4-b0ba-11e6-8ed6-d304b95ecd91.png)
1 - alignment to center (relative other text columns)
2 - move to up, to decrease table header field size
3 - add a horizontal separator for better readability
4 - table is not resizable when zoom up

**Comment by Iren-Melnyk** [comment]
Hi there! 
Thank you for your involvement and contribution to the Report Portal UI. We are aware that some issues need to be improved in the Report Portal. You will see the latest UI improvements in our upcoming  release.

**Comment by DzmitryHumianiuk** [comment]
will be covered with complete re-desing in version 3.0
I'd like to share some screens already, but also don't want to spoiler it )
