### ISSUE TITLE
"All Runs" button not work.

### ISSUE THREAD

**Issue by admizh** [reportportal/service-ui#52]
![2016-11-22_14-20-32](https://cloud.githubusercontent.com/assets/6014483/20520219/69a451f2-b0bf-11e6-9e74-28862fde6f25.png)
1. Set entries count on page
2. Click to expand "All Runs"

Please describe - how it should work?

**Comment by DzmitryHumianiuk** [comment]
it works as expected. 
Basically it returns you to Home screen of you project space or filter-tab, if selected.

`All runs` doesn't mean that it will return you all available launches in project. Just imaging if you have project with 10'000+ launches.
So it limited with paging size.
Button should be considered as `Home` or `root`, but we didn't find the proper naming for it.

Please suggest, if you have any.

**Comment by DzmitryHumianiuk** [comment]
@admizh button `+` (or ⌧) here for the breadcrumbs.
by clicking `+` you will see full names in breadcrumbs.
by default it shown with limited length.
