### ISSUE TITLE
Better visual areas determination for filters and tables.

### ISSUE THREAD

**Issue by admizh** [reportportal/service-ui#53]
Pls add better determination two visual areas - because it displayed mingled together - and very difficult to understand on first look
![2016-11-22_14-35-03](https://cloud.githubusercontent.com/assets/6014483/20520929/43d52106-b0c2-11e6-92bc-a45503769634.png)
I mark regions in different colors. User must immediately understand where the table and where table filtering

**Comment by Iren-Melnyk** [comment]
Agree, it's a good point. We've already divided this two areas. This improvement will be in next release.

**Comment by DzmitryHumianiuk** [comment]
covered by re-design in 3.0
