### ISSUE TITLE
Links recognition in log messages with markdown mode

### ISSUE THREAD

**Issue by sbakharev** [reportportal/service-ui#533]
Links recognition in log messages behaves incorrectly on some circumstances when using markdown mode.

**Steps to reproduce:**
1. Create a log message within a test item with this text:
!!!MARKDOWN_MODE!!! \`CODE\` 'https://anywebsite.com'
1. View the parent test item using UI.

**Expected result:** UI dislpays the log message in markdown mode with [CODE] block rendered as code and anywebsite link rendered as a link embraced with single quote characters.

**Actual result:** the right-side single quote near the link is transformed into HTML character code 039 and becomes part of the link.

This behavior probably affects other symbols apart from single quote as well, but I haven't investigated.

**Comment by sbakharev** [comment]
![screenshot-2018-01-09-12-28-30-612](https://user-images.githubusercontent.com/31010533/34713958-e3796abc-f538-11e7-9481-76bfc7e7065d.png)
upd: double quotes are processed incorrectly as well

**Comment by svettsova** [comment]
issue is not reproducible in 5.1
![image](https://user-images.githubusercontent.com/50825875/77892242-1e760a00-7294-11ea-8088-707a122071e3.png)
Also, to past video-link, you can put it like [![Watch the video](https://<s3-bucket-url>/sample-thumbnail.jpg)](https://[link_to_video])
