### ISSUE TITLE
Hiding actions buttons by default (when testRun not selected)

### ISSUE THREAD

**Issue by admizh** [reportportal/service-ui#54]
After fixing [Multiselect for test launches](https://rpp.uservoice.com/forums/247117-report-portal/suggestions/16087000-multiselect-for-test-launches), need create default behaviors for action buttons

![2016-11-22_15-16-16](https://cloud.githubusercontent.com/assets/6014483/20522293/f50c35a8-b0c8-11e6-80eb-af3354fb7bc3.png)

**Comment by Iren-Melnyk** [comment]
Many thanks for your comment. You will see a button with Multiple Actions in our next release.

**Comment by DzmitryHumianiuk** [comment]
covered with re-design on 3.0
