### ISSUE TITLE
Element for setup entries count per page 

### ISSUE THREAD

**Issue by admizh** [reportportal/service-ui#55]
I. Blinking effect: 
When click to control -> page size has changed (see bottom footer) - because input box is presented. Clicking should not affect to page size
![blink effect](https://cloud.githubusercontent.com/assets/6014483/20540495/d67c9fac-b112-11e6-932c-07c7d258de5e.gif)

II. Usability:
![2016-11-22_23-45-57](https://cloud.githubusercontent.com/assets/6014483/20542660/019f4b54-b11c-11e6-96a5-16bc61ebc437.png)
1. Click on control
2. Input box presented with empty value
3. Input box should contains value == 100, when press "Esc" button -> changes should not applied

III. Unable to click - when zoom changed >= 200% 
Browser Chrome:  54.0.2840.99 m **(64-bit)**
![2016-11-23_2-21-44](https://cloud.githubusercontent.com/assets/6014483/20544581/3d1f0a0e-b124-11e6-965f-e3f275246d64.png)

**Comment by DzmitryHumianiuk** [comment]
@lexecon please verify it in re-design branch

**Comment by lexecon** [comment]
This will be fixed in the new version

**Comment by lexecon** [comment]
Fixed in version 3.0
