### ISSUE TITLE
Widgets button on "Launches" tab

### ISSUE THREAD

**Issue by admizh** [reportportal/service-ui#57]
The button is present on two screens. I don't understand why.
For dahsboard screean - i totally agree, but for "launches" tab, it overload UI interface.
If this button needed on launches tab - then it should provide create widgets by current filter
![2016-11-23_11-39-54](https://cloud.githubusercontent.com/assets/6014483/20555202/219d9074-b17a-11e6-813b-a6dc656fe264.png)

anybody?

**Comment by DzmitryHumianiuk** [comment]
@admizh formally this button does exactly the same you've mentioned.
By clicking `Add widget` from launches view you will be able to create widget, based on current filter.

if it's not working - then it's a bug.

with re-desing in 3.0 usability will be update for filters.
