### ISSUE TITLE
Obsolete animation of widgets

### ISSUE THREAD

**Issue by sbakharev** [reportportal/service-ui#583]
Hello!

Several widgets suffer from the same flaw of blinking/repainting once in several seconds even if no changes actually occured (no new launches have recently been finished). A couple of examples are "launch statistics line chart" and "launches duration chart".

Though this bug is minor, it's pretty nasty. An open dashboard keeps diverting your attention for no reason. Meanwhile when it *should* attract your attention (new finished launch caused widget update?) - it does not.

Please fix this! Thank you!

**Comment by lexecon** [comment]
this will be fixed with the release of version 4.0
