### ISSUE TITLE
No way to filter items by tags they do not contain

### ISSUE THREAD

**Issue by sbakharev** [reportportal/service-ui#613]
Hi guys!

Imagine our situation: 1500+ of automated web service tests.

After some launch we find out that 300 tests have failed. So we open up the list of failed tests and see that almost all of the tests on the first page have a specific tag "TAG_1" attached which denotes some part of the product functionality that the tests involve.

But we are professionals, so we must make sure that all of the 300 failed tests have failed for the same reason!

So we click on that "TAG_1" to filter all other failed tests out, than we scroll down to the bottom of the page (since it's the only place on tests lists page that shows the total count of displayed items) and see "1 - 50 of 296"... Wow, _wth_...! So we scroll back to top, remove the "TAG_1" from the filter, (_best part starts here_) open up Chrome's search dialog via `CTRL+F`, manually type in "TAG_1" and start visually searching for items where it's missing. _So much fun._ Sooner or later after going through a couple of pages we finally see a failed test without our beloved "TAG_1", but it contains "TAG_2". So we click on "TAG_2" and get "1 - 1 of 1"... Ok, let's go back... And so on.

So please add filtering by "not contains" for tags. The situation I've just described keeps happening pretty often.

Thank you a lot! :)

**Comment by DzmitryHumianiuk** [comment]
will be implemented
