### ISSUE TITLE
Not saved text encoding.

### ISSUE THREAD

**Issue by shaburov** [reportportal/service-ui#79]
Original log
![image](https://cloud.githubusercontent.com/assets/15269131/21437293/189af24c-c894-11e6-8960-b777ec7e0b29.png)

ReportPortal log
![image](https://cloud.githubusercontent.com/assets/15269131/21437338/5c6b8356-c894-11e6-9225-8847417e358b.png)

**Comment by DzmitryHumianiuk** [comment]
@lexecon

**Comment by e-olga** [comment]
Added to RP backlog

**Comment by aklexel** [comment]
I have the same problem, wait for fix too.

**Comment by avarabyeu** [comment]
@shaburov Oleg, could you please specify which rest resource do you call? Please, do not remove part of url after your server name :)

**Comment by avarabyeu** [comment]
@shaburov @aklexel Guys, could you please create some demo project to be able to reproduce issue? I believe you are sending request to report portal in UTF-8 while part of your data (like another request inside logs) is encoded with another encoding.

**Comment by shaburov** [comment]
[Repository with test](https://github.com/shaburov/reportportal_s-ui_issue-79_test/tree/master)

**Comment by avarabyeu** [comment]
Here is what i have on my local instance:
![Image](http://image.prntscr.com/image/19375a7fb9d445d8a9368d548ebf7f63.png)
It is displayed equally as reported. 

Closing issue as fixed in RP 3.0
