### ISSUE TITLE
Text formatting is not retained.

### ISSUE THREAD

**Issue by shaburov** [reportportal/service-ui#80]
Original log
![image](https://cloud.githubusercontent.com/assets/15269131/21437468/105d8648-c895-11e6-9bd0-c6562fa258f7.png)

ReportPortal log
![image](https://cloud.githubusercontent.com/assets/15269131/21437485/2519434c-c895-11e6-8718-2efbe9de64dd.png)

**Comment by DzmitryHumianiuk** [comment]
@shaburov that one is currently in progress

**Comment by aklexel** [comment]
Great! I hope it will be soon fixed.

**Comment by lexecon** [comment]
Fixed in version 3.0
