### ISSUE TITLE
The default count of the results includes a test classes.

### ISSUE THREAD

**Issue by shaburov** [reportportal/service-ui#81]
![image](https://cloud.githubusercontent.com/assets/15269131/21438375/967557b6-c899-11e6-873c-bfe5c44d2655.png)

![image](https://cloud.githubusercontent.com/assets/15269131/21438208/e90caad4-c898-11e6-8e8f-840b8488ec79.png)

**Select Method Type -> Test Class**
![image](https://cloud.githubusercontent.com/assets/15269131/21438267/24dfd3ba-c899-11e6-9707-43b1361df8a1.png)

TestNG XmlTest.class is a repository of test classes and not a test method.
Example:
```
    protected void addTestPackage(String name, XmlClass... classes) {
        XmlTest test = new XmlTest(this);
        test.setName(name);
        List<XmlClass> classesList = new ArrayList<>();
        Collections.addAll(classesList, classes);
        test.setXmlClasses(classesList);
    }
```
```
public class AdminApiSuite extends BaseTestSuite {
    public AdminApiSuite() {
        super("Admin API test suite");
        addTestPackage("Common",
                new XmlClass("<class path>")
        );
    }
}
```

**There should be no use of "test packages" in the counting results for the tests.**

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu ?

**Comment by avarabyeu** [comment]
After the next release, different statistics calculation strategies are supposed to be introduced. For now it's not an issue and expected behaviour
