### ISSUE TITLE
Please fix failed build

### ISSUE THREAD

**Issue by AnastasiiaKravets** [reportportal/service-ui#826]
Last build was failed which caused to absence of UI part with error '404 page not found'

**Comment by evjlobanova** [comment]
@AnastasiiaKravets could you please give more details? Is it local instance or epam?

**Comment by AnastasiiaKravets** [comment]
@evjlobanova
It is local instance, launched with your manual 
<img width="585" alt="screen shot 2018-06-21 at 1 50 25 pm" src="https://user-images.githubusercontent.com/22433504/41714844-45dba6ba-755a-11e8-84bb-d7ac6ecc0de8.png">

and after successful docker launch user have such response
<img width="1021" alt="screen shot 2018-06-21 at 1 53 09 pm" src="https://user-images.githubusercontent.com/22433504/41714919-8aa1f808-755a-11e8-878b-0eed8d7626a8.png">

It appeared yesterday near the afternoon
I've tried to change Ui service version to earlier one, but result is still the same.
Thank you

**Comment by e-olga** [comment]
hi @AnastasiiaKravets

**Comment by AnastasiiaKravets** [comment]
@e-olga of course

<img width="1749" alt="screen shot 2018-06-21 at 3 00 06 pm" src="https://user-images.githubusercontent.com/22433504/41717901-eaf0ce7e-7563-11e8-8615-c4018bede081.png">

**Comment by e-olga** [comment]
provide please data from consul by http://localhost:8500/ui/#/dc1/services

**Comment by AnastasiiaKravets** [comment]
Unfortunately there is no data for ui service
<img width="1223" alt="screen shot 2018-06-21 at 3 37 51 pm" src="https://user-images.githubusercontent.com/22433504/41719642-4ee68540-7569-11e8-9e2f-dc1cc054b5d5.png">

**Comment by pbortnik** [comment]
probably there are some issues with docker cache or smth.
try to remove all containers, clear cache by command 'docker-compose system prune' and make docker-compose up again.
it should help. your data is saved.

**Comment by AnastasiiaKravets** [comment]
This was really problem with cache, but this was some PC cache, not dockers. Problem was solved with start containers from another folder.
Thank you!
