### ISSUE TITLE
The "START TIME" in Launches table haven't been i18n but use RU instead

### ISSUE THREAD

**Issue by AprilPark1012** [reportportal/service-ui#993]
Hello,

Thanks for you localization and I try to get a Chinese version for i18n. However, i found that the "START TIME" haven't been written in localizations folder(en-EU.js or ru-RU.js), and it use Russian instead. Coud you please add the keyword into localization file so that we can have it translated.

![image](https://user-images.githubusercontent.com/24444902/46853366-67cc6280-ce30-11e8-98fa-9c775603846d.png)

![image](https://user-images.githubusercontent.com/24444902/46853386-774bab80-ce30-11e8-9025-a38c64b77f86.png)

**Comment by DzmitryHumianiuk** [comment]
😲 @AprilPark1012 will you send us PR with Chinese file version?

**Comment by DzmitryHumianiuk** [comment]
@AprilPark1012 we use Moment.js for this part
they have separate config for it: https://momentjs.com/docs/#/i18n/

UI-guys will take a look, most probably we have to address global change of LOCALE globally. 
or just add Chinese version of file into static code part.

**Comment by AprilPark1012** [comment]
Already add a PR for it, please have a check.

**Comment by DzmitryHumianiuk** [comment]
@AprilPark1012 is it in `service-ui`?
Can’t find it

cc @DiscoElevator
